<?php
/**
 * @var Magento\Backend\Block\Template $block
 */

$parent = $block->getParentBlock();
$item = $parent->getItem();
$productOptions = $item->getProductOptions();
if (!isset($productOptions['info_buyRequest']['it_goes_forward'])) {
    return;
}
$itGoesForward = $productOptions['info_buyRequest']['it_goes_forward'];
?>

<tr>
    <td>
        <strong>
            <img src="<?= $block->getViewFileUrl('Aravis_ItGoesForward::images/sustainability.png'); ?>"
                 width="18"
                 height="18"
                 style="float:left;margin-right:5px;"
            />
            <span>It Goes Forward listing: <?= $itGoesForward; ?></span>
        </strong>
    </td>
</tr>
